# Generated by Django 5.2.5 on 2025-08-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('email', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('ciclo_ingreso', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('OTRO', 'Otro')], max_length=50)),
                ('materia', models.ManyToManyField(to='materia.materia')),
            ],
        ),
    ]
