# Generated by Django 5.2.5 on 2025-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('materia', '0002_alter_materia_anio_alter_materia_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='materia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(related_name='estudiantes', to='materia.materia'),
        ),
    ]
