# Generated by Django 5.2.5 on 2025-10-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_remove_estudiante_materia_estudiante_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
