# Generated by Django 5.2.5 on 2025-10-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
