# Generated by Django 5.2.5 on 2025-11-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
    ]
