# Generated by Django 5.2.5 on 2025-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('bedel', 'Bedel'), ('secretaria', 'Secretaría'), ('directivo', 'Directivo')], default='directivo', max_length=20),
        ),
    ]
