# Generated by Django 5.2.5 on 2025-08-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instituto', models.CharField(max_length=100)),
                ('ciclo_lectivo', models.CharField(max_length=100)),
            ],
        ),
    ]
