# Generated by Django 5.2.5 on 2025-08-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='numero',
        ),
    ]
