# Generated by Django 5.2.5 on 2025-10-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0002_remove_calificacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(),
        ),
    ]
