# Generated by Django 5.2.5 on 2025-11-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0003_alter_calificacion_nota'),
        ('estudiante', '0003_alter_estudiante_dni'),
        ('materia', '0002_alter_materia_anio_alter_materia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='nota_letra',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='situacion',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Abandonó', 'Abandonó'), ('Aprobó', 'Aprobó'), ('Desaprobó', 'Desaprobó'), ('AEF', 'AEF'), ('AT', 'AT')], default='En curso', max_length=20),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='materia.materia'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.CharField(max_length=10),
        ),
    ]
