# Generated by Django 5.2.5 on 2025-11-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0004_calificacion_nota_letra_calificacion_situacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='situacion',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Promocionó', 'Promocionó'), ('Abandonó', 'Abandonó'), ('Aprobó', 'Aprobó'), ('Desaprobó', 'Desaprobó'), ('AEF', 'AEF'), ('AT', 'AT')], default='En curso', max_length=20),
        ),
    ]
