# Generated by Django 5.2.5 on 2025-09-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='fecha_Nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
