# Generated by Django 5.2.5 on 2025-11-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_rename_fecha_nacimiento_docente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
