# Generated by Django 5.2.5 on 2025-08-20 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesorado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('anio', models.CharField()),
                ('profesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='profesorado.profesorado')),
            ],
        ),
    ]
