# Generated by Django 5.2.5 on 2025-09-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
        ('profesorado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='anio',
            field=models.CharField(choices=[('1', '1º Año'), ('2', '2º Año'), ('3', '3º Año'), ('4', '4º Año')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='profesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='profesorado.profesorado'),
        ),
    ]
