# Generated by Django 5.2.5 on 2025-11-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_alter_materia_anio_alter_materia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='duracion',
            field=models.CharField(choices=[('Anual', 'Anual'), ('Primer Cuatrimestre', 'Primer Cuatrimestre'), ('Segundo Cuatrimestre', 'Segundo Cuatrimestre')], default='Anual', max_length=30),
        ),
    ]
